#!/bin/bash
WORKERPORT="50005"; SERVICEPORT="50010"
export JAVA=/usr/local/bin/jdk1.7.0_51/bin
export SWIFT=/usr/local/bin/swift-0.95-RC6/bin
export PATH=$JAVA:$SWIFT:$PATH
coaster_loop ()
{
    while :
    do
        coaster-service -p $SERVICEPORT -localport $WORKERPORT -nosec -passive &> /var/log/coaster-service.logs
        sleep 10;
    done
}
coaster_loop &
