#!/bin/bash
HEADNODE=SET_HEADNODE_IP
WORKERPORT="50005"
#Ping timeout
PTIMEOUT=4
export JAVA=/usr/local/bin/jdk1.7.0_51/bin
export SWIFT=/usr/local/bin/swift-0.95-RC6/bin
export PATH=$JAVA:$SWIFT:$PATH
worker_loop ()
{
    while :
    do
        echo "Pinging HEADNODE on $HEADNODE"
        worker.pl http://$HEADNODE:$WORKERPORT 0099 ~/workerlog -w 3600
        sleep 5
    done
}
worker_loop &
